config/routes.rb
Pomometer::Application.routes.draw do

  get "reports/index"

  get "reports/show"

  get "/reports/all" => "reports#all"
  post "/reports/all" => "reports#all"

  match "reports/all" => "reports#all"
  match "reports/statistics" => "reports#statistics"
  match "reports/:id" => "reports#show"
  
  match "reports/" => "reports#index"

  match "sessions/destroy" => "sessions#destroy"

  resources :admins

  resources :milestones

  resources :results

  resources :tasks do
    collection do
      post :set_time_zone
    end
  end

  resources :milestones do
    collection do
      post :set_time_zone
    end
  end

  resources :projects

  resources :sessions

  root to: 'projects#index'

end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
  attr_accessible :ends_at, :name, :starts_at, :project_id

  belongs_to :project
  has_many :tasks
  validates :name, presence: true
  validate :end_date_after_start_date

  def end_date_after_start_date
  	if starts_at >= ends_at
		errors.add(:ends_at, " must be after Started At.")
	end 
  end
end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
  before_filter :auth_access, only: [:edit, :update, :destroy, :new, :create]

  def auth_access
    if session[:admin_id].nil?
      redirect_to root_url
    end
  end

  # GET /milestones
  # GET /milestones.json
  def index
    #figure out how to module this?
    @DEFAULT_TIME_ZONE = "Eastern Time (US & Canada)"

    if session[:selected_time_zone].nil?
      session[:selected_time_zone] = @DEFAULT_TIME_ZONE
    end

    Time.zone = session[:selected_time_zone]

    @milestones = Milestone.where(project_id: session[:current_project]).order("name ASC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @milestones }
    end
  end

  # GET /milestones/1
  # GET /milestones/1.json
  def show
    Time.zone = session[:selected_time_zone]

    @milestone = Milestone.find(params[:id])
    @tasks = Task.where(milestone_id: params[:id]).order("name ASC")

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @milestone }
    end
  end

  # GET /milestones/new
  # GET /milestones/new.json
  def new
    Time.zone = session[:selected_time_zone]

    @milestone = Milestone.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @milestone }
    end
  end

  # GET /milestones/1/edit
  def edit
    Time.zone = session[:selected_time_zone]

    @milestone = Milestone.find(params[:id])
  end

  # POST /milestones
  # POST /milestones.json
  def create
    Time.zone = session[:selected_time_zone]

    @milestone = Milestone.new(params[:milestone])

    respond_to do |format|
      if @milestone.save
        format.html { redirect_to @milestone, notice: 'Milestone was successfully created.' }
        format.json { render json: @milestone, status: :created, location: @milestone }
      else
        format.html { render action: "new" }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /milestones/1
  # PUT /milestones/1.json
  def update
    Time.zone = session[:selected_time_zone]

    @milestone = Milestone.find(params[:id])

    respond_to do |format|
      if @milestone.update_attributes(params[:milestone])
        format.html { redirect_to @milestone, notice: 'Milestone was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @milestone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milestones/1
  # DELETE /milestones/1.json
  def destroy
    @milestone = Milestone.find(params[:id])
    @milestone.destroy

    respond_to do |format|
      format.html { redirect_to milestones_url }
      format.json { head :no_content }
    end
  end

  def set_time_zone
    session[:selected_time_zone] = params[:selected_time_zone]

    respond_to do |format|
      if request.xhr?
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/views/milestones/_form.html.erb
<%= form_for(@milestone) do |f| %>
  <% if @milestone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@milestone.errors.count, "error") %> prohibited this milestone from being saved:</h2>

      <ul>
      <% @milestone.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :starts_at %><br />
    <%= f.datetime_select :starts_at %>
  </div>
  <div class="field">
    <%= f.label :ends_at %><br />
    <%= f.datetime_select :ends_at %>
  </div>
  <%= f.hidden_field :project_id, value: session[:current_project] %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/milestones/edit.html.erb
<div class='formwrapper'>
<h1>Editing Milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', milestones_path %>
</div>

app/views/milestones/index.html.erb
<h1>Current Milestones</h1>
<% if session[:admin_id] != nil %>
  <h4><%= link_to 'New Milestone', new_milestone_path %></h4>
<% end %> 

<table class='table table-striped'>
  <% if @milestones.empty? %>
    <thead>
      <tr>
        <td>
          <h2 style="text-align:center">You don't have any milestones added yet.</h2>
        </td>
      </tr>
    </thead>
  <% else %>
    <thead>
      <tr class='table_header'>
        <th>Name</th>
        <th>Starts at</th>
        <th>Ends at</th>
        <th></th>
        <% if session[:admin_id] != nil %>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% @milestones.each do |milestone| %>
        <tr class="<%= cycle('alternating_even', 'alternating_odd') -%>">
          <td><%= link_to milestone.name, milestone %></td>
          <td><%= milestone.starts_at.in_time_zone %></td>
          <td><%= milestone.ends_at.in_time_zone %></td>
        
          <% if session[:admin_id] != nil %>
            <td><%= link_to 'Edit', edit_milestone_path(milestone) %></td>
            <td><%= link_to 'Delete', milestone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

<script>
  //on dropdown changed value, we will get it's new value, and update our session variable holding time zone to that new value, and refresh the page.
  $('#user_time_zone').bind('change', function() {
      var selected_time_zone_value = $('#user_time_zone').val()

      $.post("/milestones/set_time_zone", {selected_time_zone : selected_time_zone_value}, function(data)
      {
        location.reload();
      });
    });
</script>

app/views/milestones/new.html.erb
<div class='formwrapper'>
<h1>New milestone</h1>

<%= render 'form' %>

<%= link_to 'Back', milestones_path %>
</div>

app/views/milestones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @milestone.name %>
  <% if session[:admin_id] != nil %>
     | <%= link_to 'Edit', edit_milestone_path(@milestone) %> 
  <% end %>
</p>

<p>
  <b>Starts at:</b>
  <%= @milestone.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%= @milestone.ends_at %>
</p>

<table class='table table-striped'>
  <% if @tasks.empty? %>
    <thead>
      <tr>
        <td style='text-align:center'><em>This milestone has no associated tasks yet.</em></td>
      </tr>
    </thead>
  <% else %>
    <thead>
      <tr>
    		<td>Task Name</td>
    		<td>Project Name</td>
    	</tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.name, task %></td>
          <td><%= task.project.name %></td>
          <% if session[:admin_id] != nil %>
            <td><%= link_to 'Edit', edit_task_path(task) %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>