config/routes.rb
Pomometer::Application.routes.draw do

  get "reports/index"

  get "reports/show"

  get "/reports/all" => "reports#all"
  post "/reports/all" => "reports#all"

  match "reports/all" => "reports#all"
  match "reports/statistics" => "reports#statistics"
  match "reports/:id" => "reports#show"
  
  match "reports/" => "reports#index"

  match "sessions/destroy" => "sessions#destroy"

  resources :admins

  resources :milestones

  resources :results

  resources :tasks do
    collection do
      post :set_time_zone
    end
  end

  resources :milestones do
    collection do
      post :set_time_zone
    end
  end

  resources :projects

  resources :sessions

  root to: 'projects#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :completed, :description, :effort, :name, :project_id, :milestone_id
  belongs_to :project
  belongs_to :milestone
  has_many :results
  
  validates :name, :description, :effort, :project_id, :presence => true

  #Will return all tasks, the tasks without a milestone, then the tasks with/ordered by milestone
  def self.task_list_find_and_separation(sent_project_id)
  	@tasks = Task.where("project_id = ? AND milestone_id IS NOT NULL", sent_project_id).order("milestone_id, lower(name) ASC")
    @tasks_without_milestone = Task.where(project_id: sent_project_id, milestone_id: nil).order("lower(name) ASC")
    @tasks_by_milestone = @tasks.group_by { |task| Milestone.find(task.milestone_id).name.downcase }

    return @tasks, @tasks_without_milestone, @tasks_by_milestone
  end

  #Will return all tasks, the tasks without a milestone, then the tasks with/ordered by milestone
  def self.date_filtered_task_list_find_and_separation(sent_project_id, sent_start_date, sent_end_date)
  	#all tasks within date range
  	@results = Result.where(started_at: sent_start_date.beginning_of_day..sent_end_date.end_of_day)
  	#get array of valid task ids
  	@task_ids = []
  	@results.each do |result|
  		@task_ids << result.task_id
  	end
  	#ensure unique task ids, don't need to repeat same task repeatedly
  	@task_ids.uniq

  	#get tasks that match above task_ids, AND project id
  	@tasks = Task.where(id: @task_ids, project_id: sent_project_id, milestone_id: !nil)
  	@tasks_without_milestone = Task.where(id: @task_ids, project_id: sent_project_id, milestone_id: nil)
  	@tasks_by_milestone = @tasks.group_by { |task| Milestone.find(task.milestone_id).name.downcase }

  	return @tasks, @tasks_without_milestone, @tasks_by_milestone
  end  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :auth_access, only: [:edit, :update, :destroy, :new, :create]

  def auth_access
    if session[:admin_id].nil?
      redirect_to root_url
    end
  end
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.order("name ASC")
    session[:current_task] = nil 
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    #figure out how to module this?
    @DEFAULT_TIME_ZONE = "Eastern Time (US & Canada)"

    if session[:selected_time_zone].nil?
      session[:selected_time_zone] = @DEFAULT_TIME_ZONE
    end

    Time.zone = session[:selected_time_zone]

    @task = Task.find(params[:id])

    if params[:keep_filter].nil?
      @results = Result.where(task_id: params[:id]).order("lower(goal) ASC")
    else
      #session will only be blank if user tries to intentionally break the website
      #and screw those users.
      if session[:start_date].nil?
        @results = Result.where(task_id: params[:id]).order("lower(goal) ASC")
      else
        @results = Result.where(started_at: session[:start_date].beginning_of_day..session[:end_date].end_of_day, task_id: params[:id]).order("lower(goal) ASC")
      end
    end

    session[:current_task] = params[:id]
    if @task.milestone_id.nil?
      session[:current_milestone] = nil
    else
      session[:current_milestone] = Milestone.find(@task.milestone_id)
    end
    
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    @task = Task.new
    @project = Project.find(session[:current_project])
    @milestones = Milestone.where(project_id: session[:current_project]).map{ |m| [ m.name, m.id ] }
    session[:current_task] = nil 
  end

  # GET /tasks/1/edit
  def edit
    @task = Task.find(params[:id])
    @project = Project.where(:id => @task.project_id).all
    @milestones = Milestone.all.map{ |m| [ m.name, m.id ] }
    @effort_selected = @task.effort
    @milestone_selected = @task.milestone_id
    @completed_selected = @task.completed
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(params[:task])
    #@project = Project.where(:id => @task.project_id).all
    @project = Project.find(session[:current_project])
    @milestones = Milestone.where(project_id: session[:current_project]).map{ |m| [ m.name, m.id ] }
    session[:current_task] = @task.id

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    @task = Task.find(params[:id])
    @project = Project.where(:id => @task.project_id).all

    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @project, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task = Task.find(params[:id])
    @project = Project.where(:id => @task.project_id).all
    @task.destroy

    respond_to do |format|
      format.html { redirect_to @project }
      format.json { head :no_content }
    end
  end

  def set_time_zone
    session[:selected_time_zone] = params[:selected_time_zone]
    task = Task.find(params[:id])

    respond_to do |format|
      if request.xhr?
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :completed %><br />
    <%= f.select :completed, options_for_select({:No => false, :Yes => true}, selected: @effort_selected) %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :effort %><br />
    <%= f.select :effort, options_for_select({1 => "1", 2 => "2", 3 => "3", 5 => "5", 8 => "8"}, selected: @effort_selected) %>
  </div>
  <div class="field">
    <%= f.label :milestone %><br />
    <%= f.select :milestone_id, options_for_select(@milestones, selected: @milestone_selected), :include_blank => "No Milestone" %>
  </div>
  <div class="field">
    <%= f.hidden_field :project_id, value: session[:current_project] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class='formwrapper'>
<h1>Editing task - <%= Project.find(session[:current_project]).name %></h1>

<%= render 'form' %>

<%= link_to 'Back', @project %>
</div>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>


  <table>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Effort</th>
      <th>Project</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.description %></td>
        <td><%= task.effort %></td>
        <td><%= task.project_id %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
<% end %>
<br />

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<div class='formwrapper'>
<h1>New Task - <%= @project.name %></h1>

<%= render 'form' %>
<br/>
<%= link_to 'Projects List', projects_path %>
</div>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p></div>
<div class= "task_id" data-id= <%= params[:id] %> style= "display: none;"></div>
  

    <h1><%=@task.name%></h1>
    <% if session[:admin_id] != nil %>
        <h4><%= link_to 'New Result', new_result_path %></h4>
    <% end %>
  

<div class='row'>
  <div class='span2'><%= time_zone_select( "user", "time_zone", nil, default: session[:selected_time_zone] )%></div>
  <div class='span4'></div>
  <div class='span2'></div>
</div>



<table class='table'>  
  <% if @results.empty? %>
  <tbody>
    <tr>
      <td>
        <h2 style="text-align:center">You don't have any results added yet, please add results above.</h2>
      </td>
    </tr>
  </tbody>
  <% else %>
  <thead>
  	<tr class='table_header'>
  		<td width='10%'>Goal</td>
  	  <td width='30%'>Notes</td>
  	  <td width='15%' style='text-align: center;'>Started At</td>
  	  <td width='10%'>Duration</td>
  	  <td width='15%' style='text-align: center;'>Ended At</td>
  	</tr>
  </thead>
  <tbody>
    <% @results.each do |result| %>
    	<tr class="<%= cycle('alternating_even', 'alternating_odd') -%>">
        <td><%= link_to result.goal, edit_result_path(result) %></td>
        <td><%= result.notes %></td>
        <td style="text-align:center" id=<%="started_at_"+result.id.to_s%>><%=result.started_at.in_time_zone %></td>
        <!--.in_time_zone("Eastern Time (US & Canada)")-->
        <td style="text-align:center"><%= result.duration %> mins</td>
        <td style="text-align:center" id=<%="ended_at_"+result.id.to_s%>><%= result.ended_at.in_time_zone %></td>
        <% if session[:admin_id] != nil %>
          <td class='hidable' style="text-align:center"><%= link_to 'Edit', edit_result_path(result) %></td>
          <td class='hidable' style="text-align:center"><%= link_to 'Delete', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  <% end %>
</table>

<script>
  //on dropdown changed value, we will get it's new value, and update our session variable holding time zone to that new value, and refresh the page.
  $('#user_time_zone').bind('change', function() {
      var selected_time_zone_value = $('#user_time_zone').val()
      var task_id = $(".task_id").attr("data-id");

      console.log(task_id)

      $.post("/tasks/set_time_zone", {selected_time_zone : selected_time_zone_value, id : task_id}, function(data)
      {
        location.reload();
      });
    });
</script>