config/routes.rb
Pomometer::Application.routes.draw do

  get "reports/index"

  get "reports/show"

  get "/reports/all" => "reports#all"
  post "/reports/all" => "reports#all"

  match "reports/all" => "reports#all"
  match "reports/statistics" => "reports#statistics"
  match "reports/:id" => "reports#show"
  
  match "reports/" => "reports#index"

  match "sessions/destroy" => "sessions#destroy"

  resources :admins

  resources :milestones

  resources :results

  resources :tasks do
    collection do
      post :set_time_zone
    end
  end

  resources :milestones do
    collection do
      post :set_time_zone
    end
  end

  resources :projects

  resources :sessions

  root to: 'projects#index'

end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name

  has_many :tasks
  has_many :milestones
  validates :name, :presence => true
  validates :name, :uniqueness => true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :auth_access, only: [:edit, :update, :destroy, :new, :create]

  def auth_access
    if session[:admin_id].nil?
      redirect_to root_url
    end
  end

  # GET /projects
  # GET /projects.json

  def index
    @projects = Project.order("lower(name) ASC")
    session[:current_project] = nil 
    session[:current_task] = nil 
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])
    @milestones = Milestone.order("lower(name) ASC")

    if params[:keep_filter].nil?
      @tasks, @tasks_without_milestone, @tasks_by_milestone = Task.task_list_find_and_separation(params[:id])
    else
      #session will only be blank if user tries to intentionally break the website
      #and screw those users.
      if session[:start_date].nil?
        @tasks, @tasks_without_milestone, @tasks_by_milestone = Task.task_list_find_and_separation(params[:id])
      else
        @tasks, @tasks_without_milestone, @tasks_by_milestone = Task.date_filtered_task_list_find_and_separation(params[:id], session[:start_date], session[:end_date])
      end
    end
    
    session[:current_project] = @project.id
    session[:current_task] = nil  
    session[:current_milestone] = nil
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new
    session[:current_project] = nil 
    session[:current_task] = nil 
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    session[:current_project] = @project.id

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class='formwrapper'>

<h1>Editing project</h1>
	<%= render 'form' %>

	<%= link_to 'Show', @project %> |
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p></div>
  

<h1>Project List</h1><h4><%= link_to 'New Project', new_project_path %></h4></div>
  
<table class='table-nonfluid'>
<% @projects.each do |project| %>
  <% if session[:admin_id] != nil %>
  <tbody>
    <tr class='<%= cycle('alternating_even', 'alternating_odd') -%>'>
      <td><%= link_to project.name, project %></td>
      <td><%= link_to 'Edit', edit_project_path(project) %></td>
      <td><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  </tbody>
  <% else %>
  <tbody>
    <tr class='<%= cycle('alternating_even', 'alternating_odd') -%>'>
      <td><%= link_to project.name, project %></td>
    </tr>
  </tbody>
  <% end %>
<% end %>
<% if @projects.empty? %>
<tbody>
  <tr>
  <td><em>There are no current projects</em></td>
  </tr>
</tbody>
<% end %> 


  

app/views/projects/new.html.erb
<div class='formwrapper'>
<h1>New project</h1>
	<%= render 'form' %>
	
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p></div>
  


    <h1><%=@project.name%></h1>
    <% if session[:admin_id] != nil %>
        <h4><%= link_to 'New Task', new_task_path %></h4>
    <% end %>
  



<table class='table'>
  <% if @tasks.empty? and @tasks_without_milestone.empty? %>
  <thead>
    <tr>
      <td>
        <h2 style="text-align:center">No tasks have been added to this project yet.</h2>
      </td>
    </tr>
  </thead>
  <% else %>

    <% @tasks_by_milestone.each do |name, tasks| %>
    <thead>
      <tr>
        <td colspan="6"><h4>MILESTONE: <%= name %></h4><hr/></td>
      </tr>
        <tr class='table_header'>
          <td>Complete</td>
          <td>Name</td>
          <td>Description</td>
          <td>Effort</td>
      </tr>
    </thead>
    <tbody>
      <% tasks.each do |task| %>
    	  <tr class="<%= cycle('alternating_even', 'alternating_odd') -%>">
          <td><%= task.completed ? "Yes" : "No" %></td>
          <td><%= link_to task.name, task %></td>
          <td><%= task.description %></td>
          <td style="text-align:center"><%= task.effort %></td>
          <% if session[:admin_id] != nil %>
            <td class='hidable' style="text-align:center"><%= link_to 'Edit', edit_task_path(task) %></td>
            <td class='hidable' style="text-align:center"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
    <% if @tasks_without_milestone.present? %>
      <tr>
        <td colspan="6"><h4>TASKS WITH NO MILESTONE</h4><hr/></td>
      </tr>
        <tr class='table_header'>
          <td>Complete</td>
          <td>Name</td>
          <td>Description</td>
          <td>Effort</td>
        </tr>
      <% @tasks_without_milestone.each do |task| %>
        <tr class="<%= cycle('alternating_even', 'alternating_odd') -%>">
          <td width='10%'><%= task.completed ? "Yes" : "No" %></td>
          <td width='20%'><%= link_to task.name, task %></td>
          <td width='50%'><%= task.description %></td>
          <td width='10%' style="text-align:center"><%= task.effort %></td>
          <% if session[:admin_id] != nil %>
            <td width='10%' class='hidable' style="text-align:center"><%= link_to 'Edit', edit_task_path(task) %></td>
            <td class='hidable' style="text-align:center"><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>    
    <% end %>
  <% end %>
</table>