config/routes.rb
Pomometer::Application.routes.draw do

  get "reports/index"

  get "reports/show"

  get "/reports/all" => "reports#all"
  post "/reports/all" => "reports#all"

  match "reports/all" => "reports#all"
  match "reports/statistics" => "reports#statistics"
  match "reports/:id" => "reports#show"
  
  match "reports/" => "reports#index"

  match "sessions/destroy" => "sessions#destroy"

  resources :admins

  resources :milestones

  resources :results

  resources :tasks do
    collection do
      post :set_time_zone
    end
  end

  resources :milestones do
    collection do
      post :set_time_zone
    end
  end

  resources :projects

  resources :sessions

  root to: 'projects#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pomometer</title>
  <%= stylesheet_link_tag    'application', media: 'screen' %>  
  <%= stylesheet_link_tag    'printing', media: 'print' %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js" %>
  <%= javascript_include_tag "application" %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tags %>  
</head>
<body style='background-color:#c8c8c8'>
<div class='container'>
	<div class='row'>
		<div class='span1'>
			
      
		</div>
		<div class='span10' style='background-color:white'>
        <img src="/assets/pomo.png" alt="pomo"></img><img src="/assets/pomo.png" alt="pomo"></img><img src="/assets/pomo.png" alt="pomo"></img>
			   <h1>Welcome to the Pomometer!</h1>
		  	 <h3><em>Helping you manage Projects, Tasks, and Time!</em></h3>
			   <% if session[:admin_id] != nil %>
				  <h4 style="color:green">Welcome Administrator</h4>
			   <% end %>
		</div>
		<div class='span1'>
		</div>
	</div>
	<div class='row'>
		<div class='span1 panel' id='left_panel'>
		</div>
		<div class='span10 panel' id='main_panel' style='background-color:white'>
      <div class='content_padding'>
			  <div class="navbar" id='centered' style='width:100%'>  
  				<div class="navbar-inner">  
    				<div class="container-fluid">  
    					<ul class="nav"> 

    						<% if session[:admin_id].nil? %> 

  								<li><%= link_to 'Projects', projects_path %></li> 
  								<% if session[:current_project] != nil %>
			   						<li><%= link_to 'Tasks', Project.find(session[:current_project])%></li>
			    					<% if session[:current_task] != nil %>
				    					<li><%= link_to 'Results', Task.find(session[:current_task]) %></li>
			    					<% end %>
			    	            	<li><%= link_to 'Milestones', milestones_path %></li>
			    				<% end %> 
			    			<li><%= link_to 'Reports', :controller => :reports, :action => :index %></li>
			    			<li><%= link_to 'Login', new_session_path %></li>

  							<% else %>

                  <li><%= link_to 'Projects', projects_path %></li>
                  <li><%= link_to 'Create a Project', new_project_path %></li>
                  <% if session[:current_project] != nil %>
                    <li><%= link_to 'Task List', Project.find(session[:current_project])%></li>  
                    <li><%= link_to 'Create a Task', new_task_path %></li> 
                    <% if session[:current_task] != nil %>
                      <li><%= link_to 'Result List', Task.find(session[:current_task]) %></li>  
                      <li><%= link_to 'Create a Result', new_result_path %></li>
                    <% end %>
                    <li><%= link_to 'Milestones', milestones_path %></li>
                  <% end %>
                  <li><%= link_to 'Reports', :controller => :reports, :action => :index %></li>
                  <li><%= link_to 'Admins', admins_path %></li>
                  <li><%= link_to 'Logout', :controller => :sessions, :action => :destroy %></li>

  								<!-- <li class='dropdown'>
  									<a href="#" class="dropdown-toggle" data-toggle="dropdown">Projects<b class="caret"></b></a> 
  									<ul class="dropdown-menu">  
     									<li><%= link_to 'Projects List', projects_path %></li>  
 										<li><%= link_to 'Create a Project', new_project_path %></li>    
    								</ul> 
    							</li>
    							<% if session[:current_project] != nil %>
  									<li class='dropdown'>
  										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Tasks<b class="caret"></b></a> 
  										<ul class="dropdown-menu">  
     										<li><%= link_to 'Task List', Project.find(session[:current_project])%></li>  
 											<li><%= link_to 'Create a Task', new_task_path %></li>    
    									</ul> 
    								</li>
    								<% if session[:current_task] != nil %>
    									<li class='dropdown'>
										<a href="#" class="dropdown-toggle" data-toggle="dropdown">Results<b class="caret"></b></a> 
  										<ul class="dropdown-menu">  
     										<li><%= link_to 'Result List', Task.find(session[:current_task]) %></li>  
 											<li><%= link_to 'Create a Result', new_result_path %></li>    
    									</ul> 
    									</li>
    								<% end %> -->
    								<!-- <li><%= link_to 'Milestones', milestones_path %></li>
    							<% end %>
    							<li><%= link_to 'Reports', :controller => :reports, :action => :index %></li>
    							<li><%= link_to 'Admins', admins_path %></li>
    							<li><%= link_to 'Logout', :controller => :sessions, :action => :destroy %></li>
 -->
  							<% end %>	 
						</ul>    
    				</div>  
  				</div>  
			</div> 
			    <hr/>
			    <table class='table' id='centered'>
					<%= yield %>
				</table>
		</div>
  </div>
		<div class='span1 panel' id='right_panel'>
		</div>

	</div>
</div>
</body>
</html>
<script>
  boxes = $('.panel');

  maxHeight = Math.max.apply(
  	Math, boxes.map(function() {
      return $(this).height();
    }).get());

  boxes.height(maxHeight);
</script>